EscuelaApp/Controllers/AlumnoController.cs
using EscuelaApp.Data;
using EscuelaApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EscuelaApp.Controllers
{
    [Route("/alumnos")]
    public class AlumnoController : Controller
    {
        private EscuelaDbContext _context;

        public AlumnoController(EscuelaDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            var ALUMNOS = _context.Alumnos.ToList();

            return View(ALUMNOS);
        }

        [HttpGet("/alumnos/detalles/{id?}")]
        public IActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id)) 
            {
                return RedirectToAction("Index");
            }

            var ALUMNO = from alumno in _context.Alumnos
                         where alumno.Id == id
                         select alumno;

            return View(ALUMNO.SingleOrDefault());
        }

    }

}

EscuelaApp/Controllers/AsignaturaController.cs
using EscuelaApp.Data;
using EscuelaApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EscuelaApp.Controllers
{
    [Route("/Asignaturas")]
    public class AsignaturaController : Controller
    {
        private EscuelaDbContext _context;
        public AsignaturaController(EscuelaDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var ASIGNATURAS = _context.Asignaturas.ToList();

            return View(ASIGNATURAS);
        }

        [HttpGet("detalles/{id?}")]
        public IActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            var ASIGNATURA = from asig in _context.Asignaturas
                             where asig.Id == id
                             select asig;

            return View(ASIGNATURA.SingleOrDefault());
        }
    }
}

EscuelaApp/Controllers/CursoController.cs
using EscuelaApp.Data;
using EscuelaApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EscuelaApp.Controllers
{
    [Route("/Cursos")]
    public class CursoController : Controller
    {
        private EscuelaDbContext _context;

        public CursoController(EscuelaDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            var CURSOS = _context.Cursos.ToList();

            return View(CURSOS);
        }

        [HttpGet("/Cursos/Detalles/{id?}")]
        public IActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id)) 
            {
                return RedirectToAction("Index");
            }

            var CURSO = from curso in _context.Cursos
                         where curso.Id == id
                         select curso;

            return View(CURSO.SingleOrDefault());
        }

        [HttpGet("Nuevo")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Nuevo")]
        public IActionResult Store(Curso curso)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", curso);
            }

            var escuela = _context.Escuelas.FirstOrDefault();
            curso.EscuelaId = escuela.Id;

            _context.Cursos.Add(curso);
            _context.SaveChanges();
            ViewBag.Mensaje = "Curso creado satisfatoriamente";

            return View("Details", curso);
        }

        [HttpGet("Editar/{id?}")]
        public IActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            var CURSO = from curso in _context.Cursos
                        where curso.Id == id
                        select curso;

            return View(CURSO.FirstOrDefault());
        }

        [HttpPost("Editar")]
        public IActionResult Update(Curso curso)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", curso);
            }

            var cursoActualizar = (from c in _context.Cursos
                                   where c.Id == curso.Id
                                   select c).FirstOrDefault();

            if (cursoActualizar == null)
            {
                return NotFound();
            }

            cursoActualizar.Nombre = curso.Nombre;
            cursoActualizar.Jornada = curso.Jornada;
            cursoActualizar.Dirección = curso.Dirección;          
            _context.SaveChanges();

            ViewBag.Mensaje = "Curso Actualizado Exitosamente";

            return View("Edit", curso);
        }

    }

}

EscuelaApp/Controllers/EscuelaController.cs
using EscuelaApp.Data;
using EscuelaApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EscuelaApp.Controllers
{
    public class EscuelaController : Controller
    {
        private EscuelaDbContext _context { get; set; }
        public EscuelaController(EscuelaDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var ESCUELA = _context.Escuelas.FirstOrDefault();

            return View(ESCUELA);
        }
    }
}

EscuelaApp/Views/Shared/_DetailsObjectPartial.cshtml
@model IModelBase

<div class="jumbotron">
    <div class="container text-center">
        <h1 class="display-4">@Model.Nombre</h1>
        <hr class="my-4">
        <p class="lead text-muted">@Model.Id</p>
    </div>
</div>

EscuelaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Escuela Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Escuela" asp-action="Index">Escuela</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Asignatura" asp-action="Index">Asignaturas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Alumno" asp-action="Index">Alumnos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Escuela Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EscuelaApp/Views/Shared/_TablaObjetoPartial.cshtml
@*
    @model List<ObjetoEscuelaBase>
*@


<div class="card">
    <table class="table table-hover">
        <thead class="bg-dark text-light">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Controles</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
            <tr>
                <td>@obj.Id</td>
                <td>@obj.Nombre</td>
                <td>
                    <a class="btn btn-link" asp-action="Edit" asp-route-id="@obj.Id">Editar</a> |
                    <a class="btn btn-link" asp-action="Details" asp-route-id="@obj.Id">Detalles</a>
                            </td>
            </tr>
            }
        </tbody>
    </table>
</div>